on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates feeds and stats

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          feed_list: "https://avelino.run/index.xml"

      - name: Github projects contributer
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: GITHUB
          feed_list: "https://github.com/avelino.atom"
